### PR TITLE
add ansible playbook for native-setup

### PR DESCRIPTION
**Pull request by dmdhrumilmistry**
Adds feature for https://github.com/PhonePe/mantis/issues/48

### CODE REVIEW

**Comment by 0xbharath** [comment]
Will review this today.

**Comment by dmdhrumilmistry** [comment]
@0xbharath did you get time to review it?

**Comment by 0xbharath** [comment]
Hi @dmdhrumilmistry 

This looks good but needs some changes to be more useful. I'll share my comments on this in a bit. Excuse the delay as I'm on break for a few days.

**Comment by dmdhrumilmistry** [comment]
> Hi @dmdhrumilmistry
> 
> This looks good but needs some changes to be more useful. I'll share my comments on this in a day. Excuse the delay as I'm on break for a few days.

No worries, lemme know, if you have something in mind.

**Comment by 0xbharath** [comment]
This commit is not merged. This needs changes. I'll share comments here.

**Comment by dmdhrumilmistry** [comment]
> This commit is not merged. This needs changes. I'll share comments here.

Ack! I'll reraise a new PR for this

**Pull request merged**
