### PR TITLE
Add features as described in Issue 37

### PR DESCRIPTION
**Pull request by dmdhrumilmistry**
Issue Link: https://github.com/PhonePe/mantis/issues/37

* Flag for listing org

```bash
python launch.py list --list-orgs
python launch.py list -l
```

* List domains for org

```bash
python launch.py list --list-domains --org "org1" --org "org2" --tlds # list TLDs for multiple orgs
python launch.py list --list-domains --org "org1" --org "org2" --subs # list subdomains for multiple orgs
python launch.py list --list-domains --org "org1" --org "org2" --tlds --subs # list TLDs + subdomains for multiple orgs

python launch.py list -d -o "org1" -o "org2" -t # list TLDs for multiple orgs
python launch.py list -d -o "org1" -o "org2" -s # list subdomains for multiple orgs
python launch.py list -d -o "org1" -o "org2" -t -s # list TLDs + subdomains for multiple orgs
```

* Time based filter

```bash
python launch.py list -tds -o "org1" -a 2024-09-04 -b 2024-09-05 # list TLDs + subdomains for org1 in timeframe [2024-09-04, 2024-09-05]
```

> [!NOTE]  
> `-a`/`--after` and `-b`/`--before` filters can be used individually as well

Checklist:
- [ ] Merge https://github.com/PhonePe/mantis/pull/49
- [ ] Merge main branch into [dmdhrumilmistry:issue-37](https://github.com/dmdhrumilmistry/mantis/tree/issue-37)

### CODE REVIEW

**Comment by Prateek-Thakare** [comment]
Hi @dmdhrumilmistry 
Thanks for raising the pr. I will review this and request changes if required any.

**Comment by dmdhrumilmistry** [comment]
> Hi @dmdhrumilmistry Thanks for raising the pr. I will review this and request changes if required any.

Sure. Sg!

**Comment by 0xbharath** [comment]
@dmdhrumilmistry Thanks for the PR. This looks very good. I tested it and everything works as expected. 

Quick question, any reason to use `tds` in `list -tds -o "org1" -a 2024-09-04 -b 2024-09-05` instead of `tlds`?

Also, when i run `mantis list -tds -o "sample-org" -a 2024-01-01 -b 2024-02-02`, the time based filter works but I get all the subdomains. When i use `tds` my assumption was that I'll get only TLDs.

**Comment by dmdhrumilmistry** [comment]
> @dmdhrumilmistry Thanks for the PR. This looks very good. I tested it and everything works as expected.
> 
> Quick question, any reason for using `tds` keyword in `list -tds -o "org1" -a 2024-09-04 -b 2024-09-05` instead of `tlds`?
> 
> Also, when i run `mantis list -tds -o "sample-org" -a 2024-01-01 -b 2024-02-02`, the time based filter works but I get all the subdomains. When I use `tds`, my assumption was that I'll get only TLDs.

sg, actually tds are different flags `-t` `-d` `-s`. I've just added it for demonstration that they can be clubbed together as well (`-tds`)

|Flag|Description|
|:---:|:-----------|
|t/tlds|includes tlds in response|
|s/subs|includes subdomains in response

**Comment by 0xbharath** [comment]
Makes sense. 

@Prateek-Thakare I tested the functionality. It's good to go. Can you go through the code and merge the PR?

**Comment by Prateek-Thakare** [comment]
Hi @dmdhrumilmistry, 
Can you please remove the commits for the Ansible feature from this PR and re-raise it?

Thanks,
Prateek

**Comment by dmdhrumilmistry** [comment]
> Hi @dmdhrumilmistry, Can you please remove the commits for the Ansible feature from this PR and re-raise it?
> 
> Thanks, Prateek

Hey @Prateek-Thakare,

I've removed ansible files. LMK if any other changes are required

**Review by Prateek-Thakare — APPROVED** [review]
The code is structured well and @0xbharath has tested the flow end to end.

**Comment by dmdhrumilmistry** [comment]
@Prateek-Thakare / @0xbharath thanks for the merge 🙌. Can someone add `hacktoberfest-accepted` label to this and https://github.com/PhonePe/mantis/pull/49 PRs?

**Comment by Prateek-Thakare** [comment]
Thanks for the contribution. I have added the labels to the PRs. Looking forward to more such contributions.

**Pull request merged**
