### PR TITLE
Added Namecheap Nameserver integration

### PR DESCRIPTION
**Pull request by madhav6ram**
Closes Issue #46 

Tested using Namecheap sandbox API.

### CODE REVIEW

**Comment by 0xbharath** [comment]
@madhav6ram 

This looks good but I got an error when testing this integration. 

## What is the error

I ran mantis with your Namecheap extension but I got the following error.

```
[2024-10-16 11:02:10,072] --> INFO: MANTIS Workflow - STARTED
[2024-10-16 11:02:10,072] --> INFO: Executing workname workflowName='test' schedule='daily between 00:00 and 04:00' cmd=[] scanNewOnly=False workflowConfig=[Module(moduleNam
e='dns', tools=['Namecheap'], order=1)]

DNS:   0%|                                                                                                                                             | 0/1 [00:00<?, ?it/s]
[2024-10-16 11:02:10,102] --> INFO: Reading zone files from Namecheap nameservers
[2024-10-16 11:02:10,299] --> INFO: Enumerating domain: test.com
[2024-10-16 11:02:10,673] --> INFO: Enumerating domain: test1.com
[2024-10-16 11:02:10,789] --> INFO: Failed
DNS: 100%|█████████| 1/1 [00:00<00:00,  1.45it/s]
```

```
        {
          "tool_name": "Namecheap",
          "success": 0,
          "failure": 1,
          "code": null,
          "command": null,
          "errors": null,
          "exception": "Error in response from Namecheap: b'<?xml version=\"1.0\" encoding=\"utf-8\"?>\\r\\n<ApiResponse Status=\"ERROR\" xmlns=\"http://api.namecheap.com/xml.response\">\\r\\n  <Errors>\\r\\n    <Error Number=\"2030288\">Cannot complete this command as this domain is not using proper DNS servers</Error>\\r\\n  </Errors>\\r\\n  <Warnings />\\r\\n  <RequestedCommand>namecheap.domains.dns.gethosts</RequestedCommand>\\r\\n  <CommandResponse Type=\"namecheap.domains.dns.getHosts\">\\r\\n    <DomainDNSGetHostsResult IsUsingOurDNS=\"false\" />\\r\\n  </CommandResponse>\\r\\n  <Server>PHX01APIEXT01</Server>\\r\\n  <GMTTimeDifference>--4:00</GMTTimeDifference>\\r\\n  <ExecutionTime>0.012</ExecutionTime>\\r\\n</ApiResponse>'",
          "tool_time_taken": "0:00:01",
          "output": null
```

## Possible causes

This doesn't seem to be an issue with your code. I have two domains in my Namecheap account and this error happens when the the records are enumerated for a domain that uses external Nameserver. 

## Possible resolution

1. Namecheap doesn't allow granular control over API key permissions. Can you add a check in your integration so that only the enumeration happens for the onboarded TLDs only and not all the domains on the nameserver. I'll share sample code for this.
2. Can you add exception handling for such cases? (Optional)

**Comment by madhav6ram** [comment]
@0xbharath I will test both these suggestions and update my PR.

**Comment by 0xbharath** [comment]
You can refer to this PR https://github.com/PhonePe/mantis/pull/53

**Comment by 0xbharath** [comment]
This should be good. I'll review this and let you know.

**Comment by 0xbharath** [comment]
This has been delayed on my end. Will review this today.

**Comment by 0xbharath** [comment]
This is good from a functionality PoV. 

@Prateek-Thakare Can you go through the code and merge this?

**Review by Prateek-Thakare — APPROVED** [review]
Reviewed the code, Bharath has tested the code. Made changes to the files not needed.

**Pull request merged**
