### PR TITLE
Update multiple tools to their latest versions & deleted redundant tools

### PR DESCRIPTION
**Pull request by 0xbharath**
subfinder: 2.6.3 to 2.6.6
ipinfo: 3.1.2 to 3.3.1
Updated httpx: 1.3.7 to 1.6.8
Updated Nuclei: 3.0.4 to 3.3.4

Updated Python packages as per Github security advisories

Removed puredns
Removed Amass

### CODE REVIEW

**Comment by hiteshkumarthakur** [comment]
Hi @Prateek-Thakare @0xbharath 
I have reviewed the changes.
looks good to me

**Review by Prateek-Thakare — COMMENTED** [review]
Reviewed the dockerfile for the changes. The versions of the tools have been updated and Amass is being removed.

**Review by Prateek-Thakare — APPROVED** [review]
Merging the PR, the changes are good to merge

**Comment by 0xbharath** [comment]
@Ncoder2 Can you merge the PR and also make sure the new docker images are built and pushed to registry?

**Comment by 0xbharath** [comment]
@Ncoder2 Can you confirm if the docker images are built and pushed to registry with these changes? Looks like the job was skipped. This means the Mantis docker images still have old code.

**Pull request merged**
